### ISSUE TITLE
Getting user messages doesn't work

### ISSUE THREAD

**Issue by jacobduba** [Dylan5797/scratchapi#12]
When I tried to get Griffpatch's message count I got an error. I don't think this is my error though.

C:\Users\Jacob\AppData\Local\Programs\Python\Python35-32\python.exe C:/Users/Jacob/PycharmProjects/GriffMessages/src/me/mooshoe/Main.py
Traceback (most recent call last):
  File "C:/Users/Jacob/PycharmProjects/GriffMessages/src/me/mooshoe/Main.py", line 4, in <module>
    class Main:
  File "C:/Users/Jacob/PycharmProjects/GriffMessages/src/me/mooshoe/Main.py", line 7, in Main
    print(scratch.users.get_message_count("Griffpatch"))
  File "C:\Users\Jacob\AppData\Local\Programs\Python\Python35-32\lib\site-packages\scratchapi.py", line 175, in _users_get_message_count
    return self.lib.utils.request('/proxy/users/' + user + '/activity/count', server=self.API_SERVER).json()['msg_count']
TypeError: _rcallarg() takes 1 positional argument but 2 were given

**Comment by PolyEdge** [comment]
I am planning to add this in the next release of scratchapi, with cloud log polling and getting followings/followers (yay)

**Comment by jacobduba** [comment]
cool enclo said you gave him a script for that

**Comment by PolyEdge** [comment]
Whoops, forgot to close
