### ISSUE TITLE
Repeatedly logging in (maybe?) causes errors?

### ISSUE THREAD

**Issue by Tymewalk** [Dylan5797/scratchapi#14]
```
Traceback (most recent call last):
  File "deletejupiter/__init__.py", line 10, in <module>
    session = scratchapi.CloudSession(projectID, userSession)
  File "/usr/local/lib/python3.4/dist-packages/scratchapi.py", line 293, in __init__
    self._token = self._scratch.lib.utils.request(method='GET', path='/projects/' + str(self._projectId) + '/cloud-data.js').text.rsplit('\n')[-28].replace(' ', '')[13:49]
IndexError: list index out of range
```

This happens when trying to begin a session with a username and password sometimes.

I think it's from logging in too much, as I can wait and try again and the error is not there.

**Comment by skistaddy** [comment]
What script are you running? (Just star (*) the credentials.)

**Comment by Tymewalk** [comment]
One for a game I'm making:

```
# -*- coding: utf-8 -*-
import scratchapi, getpass, slither, json, time

projectID = 88699743

print("== DELETE JUPITER ==")
scratchUser = input("Enter your Scratch username: ")
scratchPass = getpass.getpass("Enter your Scratch password: ")
userSession = scratchapi.ScratchUserSession(scratchUser, scratchPass)
session = scratchapi.CloudSession(projectID, userSession)

scratchPass = ""
```

It crashes before it can go further.

The full code can be found [here](https://github.com/Tymewalk/DeleteJupiter/blob/master/deletejupiter/__init__.py), but I felt a lot of it was unnecessary.

**Comment by PolyEdge** [comment]
This could be database lag, or...

The scratchapi build on python2 is becoming more and more unstable, I'm probably going to drop python2 support soon. (Sorry if I'm assuming you're using python2, it's just that python3 uses utf-8 by default :wink:)

**Comment by Tymewalk** [comment]
@PolyEdge Ah. I am using Python3. :dagger: 

IDK why it needs the UTF-8 coding. IDLE added it for me when I tried to save.

**Comment by PolyEdge** [comment]
Oh. Scratch does that if you log in too much. There's no workaround, and I don't think it would be a good idea for it to wait for the cooldown...

**Comment by joker314** [comment]
Then perhaps could you consider a custom error message like "Scratch Error: Too many logins in a short amount of time"

**Comment by PolyEdge** [comment]
I'm not sure that the module could come to a conclusion quickly enough whether that was the issue or not and assuming so could cause some confusion.
